---

- block:
  - name: create partition
    parted:
      device: "{{ lvm_device_name }}"
      number: 1
      flags: [ lvm ]
      state: present
      

  - name: Install lvm2 dependency
    package:
      name: lvm2
      state: present

  - name: task for creating volume group
    lvg:
        vg: glusterfs-vg
        pvs: "{{ lvm_device_name }}1"
        pesize: 16

  - name: task for creating logical volume
    lvol:
        vg: glusterfs-vg
        lv:  glusterfs-lv
        size: 100%FREE
        force: yes

  - name: Create directory data1 if does not exist
    file:
      path: /glusterfs
      state: directory
      mode: '0755'

  - name: format the xfs filesystem
    filesystem:
      fstype: xfs
      dev: /dev/glusterfs-vg/glusterfs-lv

  - name: mount the lv on /glusterfs
    mount:
      path: /glusterfs
      src: /dev/glusterfs-vg/glusterfs-lv
      fstype: xfs
      state: mounted


