---
- name: Deploy GlusterFS cluster
  hosts: glusternodes
  gather_facts: yes
  become: true
  vars_files:
    - vars/main.yml
  vars:
    minimal_ansible_version: 2.7.0
  tasks:
    - name: Checking ansible version
      fail:
        msg: "Ansible version must be {{ minimal_ansible_version }} or higher"
      when: ansible_version.full is version(minimal_ansible_version, '<')
  
  pre_tasks:
    - name: Checking Linux distribution      
      fail:
        msg: "{{ ansible_distribution }} is not supported"
      when: ansible_distribution not in os_valid_distributions
    - name: Checking version of OS Linux
      fail:
        msg: "{{ ansible_distribution_version }} of {{ ansible_distribution }} is not supported"
      when: ansible_distribution_version is version_compare(os_minimum_versions[ansible_distribution], '<')
    - name: Checking Linux distribution
      debug: msg="Os Family {{ansible_os_family}} {{ ansible_distribution }} - {{ansible_distribution_version}} - {{ansible_distribution_major_version}}"

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      environment: "{{ proxy_env | default({}) }}"
      when: ansible_os_family == "Debian"
      tags: check_os, update_os

  roles:
    - role: disk
    - role: gluster
