- name: Reset Ansible Cluster
  hosts: glusternodes
  become: true
  gather_facts: false
  vars_files:
    - vars/main.yml
  vars:
    minimal_ansible_version: 2.7.0
  tasks:
    - name: Checking ansible version
      fail:
        msg: "Ansible version must be {{ minimal_ansible_version }} or higher"
      when: ansible_version.full is version(minimal_ansible_version, '<')


    # - name: Stop the gluster server
    #   ansible.builtin.systemd:
    #     name: glusterd
    #     enabled: yes
    #     state: stopped

    # - name: Remove glusterfs server
    #   apt:
    #     name: "{{ packages }}"
    #     state: absent
    #     purge: yes
    #   vars:
    #     packages:
    #     - glusterfs-server
    

#  Remove logical disks

    - name: Umount the lv on /data1
      mount:
        path: /glusterfs
        src: /dev/glusterfs-vg/glusterfs-lv
        fstype: xfs
        state: unmounted


    - name: Remove logical volume
      lvol:
          vg: glusterfs-vg
          lv:  glusterfs-lv          
          force: yes
          state: absent

    - name: Remove Volume Groups
      lvg:
          vg: glusterfs-vg
          pvs: "{{ lvm_device_name }}1"
          state: absent



    # Read device information (always use unit when probing)
    - parted: device=/dev/sdb unit=MiB
      register: sdb_info

    # Remove all partitions from disk
    - name: Delete all partions on {{ lvm_device_name }}
      parted:
        device: /dev/sdb
        number: "{{ item.num }}"
        state: absent
      with_items:
      - "{{ sdb_info.partitions }}"