---
# install glusterfs and create a volume in /glusterfs

- block:
  - name: Update repositories cache and install "glusterfs-server" package
    apt:
      name: glusterfs-server
      update_cache: yes

  - name: Enable service glusterd and ensure it is not masked
    ansible.builtin.systemd:
      name: glusterd
      enabled: yes
      state: started

  - name: Ensure Gluster brick and mount directories exist.
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0775
    with_items:
      - "{{ gluster_brick_dir }}"
      - "{{ gluster_mount_dir }}"

  - name: Check if Gluster volumes already exist.
    shell: "gluster volume info"
    changed_when: false
    register: gluster_volume_info

  - name: Connect to Gluster peers.
    shell: "gluster peer probe {{ item }}"
    register: gluster_peer_probe
    changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
    failed_when: false
    loop: "{{ groups['glusternodes'] }}"
    when: "'Volume Name: gluster' not in gluster_volume_info.stdout"

  - name: Create Gluster volume.
    shell: "gluster volume create {{ gluster_brick_name }} {{ gluster_brick_config }}"
    register: gluster_volume_create
    changed_when: "'successful' in gluster_volume_create.stdout"
    when: "'Volume Name: gvol0' not in gluster_volume_info.stdout"
     


...
